//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntites : DbContext
    {
        public DBEntites()
            : base("name=DBEntites")
        {
        }
    
        private static DBEntites _context;
        public static DBEntites GetContext()
        {
            if (_context == null)
                _context = new DBEntites();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<ЕдиницаИзмерения> ЕдиницаИзмерения { get; set; }
        public virtual DbSet<Заявка> Заявка { get; set; }
        public virtual DbSet<Материал> Материал { get; set; }
        public virtual DbSet<МатериалНаПродукцию> МатериалНаПродукцию { get; set; }
        public virtual DbSet<МатериалНаСкладе> МатериалНаСкладе { get; set; }
        public virtual DbSet<Место> Место { get; set; }
        public virtual DbSet<МестоПродаж> МестоПродаж { get; set; }
        public virtual DbSet<Партнер> Партнер { get; set; }
        public virtual DbSet<ПоставкаМатериала> ПоставкаМатериала { get; set; }
        public virtual DbSet<Поставщик> Поставщик { get; set; }
        public virtual DbSet<Продукция> Продукция { get; set; }
        public virtual DbSet<ПродукцияВЗаявке> ПродукцияВЗаявке { get; set; }
        public virtual DbSet<ПродукцияСклад> ПродукцияСклад { get; set; }
        public virtual DbSet<Склад> Склад { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<ТипМатериала> ТипМатериала { get; set; }
        public virtual DbSet<ТипОрганизации> ТипОрганизации { get; set; }
        public virtual DbSet<ТипПродукции> ТипПродукции { get; set; }
        public virtual DbSet<Цех> Цех { get; set; }
    }
}
