//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявка
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Заявка()
        {
            this.ПродукцияВЗаявке = new HashSet<ПродукцияВЗаявке>();
        }
    
        public int Код { get; set; }
        public Nullable<int> КодПартнер { get; set; }
        public Nullable<int> КодМенеджер { get; set; }
        public Nullable<int> КодПродукция { get; set; }
        public Nullable<System.DateTime> ДатаПродажи { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<System.DateTime> ДатаПроизводства { get; set; }
    
        public virtual Партнер Партнер { get; set; }
        public virtual Продукция Продукция { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродукцияВЗаявке> ПродукцияВЗаявке { get; set; }
    }
}
