//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Материал
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Материал()
        {
            this.МатериалНаПродукцию = new HashSet<МатериалНаПродукцию>();
            this.ПоставкаМатериала = new HashSet<ПоставкаМатериала>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public string КоличествоВУпаковке { get; set; }
        public string Описание { get; set; }
        public string Изображение { get; set; }
        public string Стоимость { get; set; }
        public Nullable<int> КодЕдиницаИзмерения { get; set; }
        public Nullable<int> КодТипМатериала { get; set; }
    
        public virtual ЕдиницаИзмерения ЕдиницаИзмерения { get; set; }
        public virtual ТипМатериала ТипМатериала { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<МатериалНаПродукцию> МатериалНаПродукцию { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПоставкаМатериала> ПоставкаМатериала { get; set; }
    }
}
