//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class МатериалНаСкладе
    {
        public int Код { get; set; }
        public Nullable<int> КодМатериалПоставщик { get; set; }
        public Nullable<int> КодСклад { get; set; }
        public Nullable<int> Количество { get; set; }
        public string МинимальноДопустимоеКоличество { get; set; }
    
        public virtual ПоставкаМатериала ПоставкаМатериала { get; set; }
        public virtual Склад Склад { get; set; }
    }
}
