//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class МестоПродаж
    {
        public int Код { get; set; }
        public Nullable<int> КодМесто { get; set; }
        public Nullable<int> КодПартнер { get; set; }
    
        public virtual Место Место { get; set; }
        public virtual Партнер Партнер { get; set; }
    }
}
