//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Партнер
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Партнер()
        {
            this.Заявка = new HashSet<Заявка>();
            this.МестоПродаж = new HashSet<МестоПродаж>();
        }
    
        public int Код { get; set; }
        public string Наименование { get; set; }
        public string ЮридическийАдрес { get; set; }
        public string ИНН { get; set; }
        public string ФИОДиректора { get; set; }
        public string Телефон { get; set; }
        public string Email { get; set; }
        public byte[] Логотип { get; set; }
        public Nullable<double> Рейтинг { get; set; }
        public Nullable<int> КодТипПартнера { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<МестоПродаж> МестоПродаж { get; set; }
        public virtual ТипОрганизации ТипОрганизации { get; set; }
    }
}
