//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПоставкаМатериала
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ПоставкаМатериала()
        {
            this.МатериалНаСкладе = new HashSet<МатериалНаСкладе>();
        }
    
        public int Код { get; set; }
        public Nullable<int> КодМатериал { get; set; }
        public Nullable<int> КодПоставщик { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<System.DateTime> Дата { get; set; }
    
        public virtual Материал Материал { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<МатериалНаСкладе> МатериалНаСкладе { get; set; }
        public virtual Поставщик Поставщик { get; set; }
    }
}
