//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Продукция
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Продукция()
        {
            this.Заявка = new HashSet<Заявка>();
            this.МатериалНаПродукцию = new HashSet<МатериалНаПродукцию>();
            this.ПродукцияВЗаявке = new HashSet<ПродукцияВЗаявке>();
            this.ПродукцияСклад = new HashSet<ПродукцияСклад>();
        }
    
        public int Код { get; set; }
        public string Артикул { get; set; }
        public string Наименование { get; set; }
        public string Описание { get; set; }
        public byte[] Изображение { get; set; }
        public Nullable<double> Высота { get; set; }
        public Nullable<double> Длина { get; set; }
        public Nullable<double> Ширина { get; set; }
        public Nullable<double> ВесБезУпаковки { get; set; }
        public Nullable<double> ВесСУпаковкой { get; set; }
        public byte[] СертификатКачества { get; set; }
        public string НомерСтандарта { get; set; }
        public Nullable<int> КодЦех { get; set; }
        public Nullable<int> КодТипПродукции { get; set; }
        public Nullable<double> МинимальнаяСтоимостьПартнеру { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<МатериалНаПродукцию> МатериалНаПродукцию { get; set; }
        public virtual ТипПродукции ТипПродукции { get; set; }
        public virtual Цех Цех { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродукцияВЗаявке> ПродукцияВЗаявке { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ПродукцияСклад> ПродукцияСклад { get; set; }
    }
}
