//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПродукцияСклад
    {
        public int Код { get; set; }
        public Nullable<int> КодПродукция { get; set; }
        public Nullable<int> КодСклад { get; set; }
    
        public virtual Продукция Продукция { get; set; }
        public virtual Склад Склад { get; set; }
    }
}
