//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ПродукцияВЗаявке
    {
        public int Код { get; set; }
        public Nullable<int> КодЗаявка { get; set; }
        public Nullable<int> КодПродукция { get; set; }
        public Nullable<System.DateTime> ДатаПроизводства { get; set; }
        public Nullable<int> Количество { get; set; }
        public Nullable<double> Стоимость { get; set; }
    
        public virtual Заявка Заявка { get; set; }
        public virtual Продукция Продукция { get; set; }
    }
}
