//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Заявка = new HashSet<Заявка>();
        }
    
        public int Код { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> ДатаРождения { get; set; }
        public string Реквизиты { get; set; }
        public Nullable<bool> НаличиеСемьи { get; set; }
        public Nullable<int> КодДолжность { get; set; }
        public Nullable<int> КодСостояниеЗдоровья { get; set; }
        public string Номер { get; set; }
        public string Серия { get; set; }
        public Nullable<System.DateTime> ДатаВыдачи { get; set; }
        public string Прописка { get; set; }
        public string МестоВыдачи { get; set; }
        public Nullable<bool> СостояниеЗдоровья { get; set; }
        public Nullable<int> КодЦех { get; set; }
    
        public virtual Должность Должность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Заявка> Заявка { get; set; }
        public virtual Цех Цех { get; set; }
    }
}
